"""replace is_done with status

Revision ID: 2c225f9e6998
Revises: e7b27688d700
Create Date: 2025-12-17 22:31:40.536874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2c225f9e6998'
down_revision: Union[str, None] = 'e7b27688d700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.drop_column('is_done')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_done', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###