"""phase_1_2_schema

Revision ID: 3698362e1754
Revises: 2c225f9e6998
Create Date: 2025-12-18 15:25:25.946110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3698362e1754'
down_revision: Union[str, None] = '2c225f9e6998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('notes',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('title', sa.String(length=100), nullable=False),
    # sa.Column('content', sa.Text(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('secrets',
    # sa.Column('key', sa.String(length=100), nullable=False),
    # sa.Column('value', sa.Text(), nullable=False),
    # sa.Column('description', sa.String(length=255), nullable=True),
    # sa.PrimaryKeyConstraint('key')
    # )
    # op.create_table('stats',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=50), nullable=False),
    # sa.Column('value', sa.Float(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('task_dependencies',
    # sa.Column('blocker_id', sa.Integer(), nullable=False),
    # sa.Column('blocked_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['blocked_id'], ['tasks.id'], ),
    # sa.ForeignKeyConstraint(['blocker_id'], ['tasks.id'], ),
    # sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    # )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_parent_id', 'tasks', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_parent_id', type_='foreignkey')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('due_date')
        batch_op.drop_column('start_date')

    op.drop_table('task_dependencies')
    op.drop_table('stats')
    op.drop_table('secrets')
    op.drop_table('notes')
    # ### end Alembic commands ###