"""phase_3_notes

Revision ID: a4d6f79644f6
Revises: 3698362e1754
Create Date: 2025-12-19 00:17:42.013484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a4d6f79644f6'
down_revision: Union[str, None] = '3698362e1754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_links',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'target_id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.drop_table('note_links')
    # ### end Alembic commands ###